---
title: "Assignment 2"
author: "RyanOConnor"
date: "r format(Sys.Date(), '%B %d, %Y')"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```
## Assignment 2
```{r}
library(devtools)
install_github('walkerke/tigris')
library(tigris)
library(tidyverse)
library(tigris) 
library(sf)
library(mapview) 
library(leaflet)
library(censusapi)
Sys.setenv(CENSUS_KEY="cccdf64b447748daaddebe5f9aeaec92fc4b744c")
```

```{r}
dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )
SMC_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_003N"
  ) %>% 
  transmute(
    GEOID20 =  paste0(state,county,tract,block),
    pop_2020 = P1_003N
  )
blocks_2020 <- blocks("CA", "San Mateo County", year = 2020, progress_bar = F)
```


```{r}
dec_vars_2010 <-
  listCensusMetadata(
    name = "2010/dec/pl",
    type = "variables"
  )
SMC_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P001003"
  ) %>% 
  transmute(
    GEOID10 = paste0(state,county,tract,block),
    pop_2010 = P001003
  )
blocks_2010 <- blocks("CA", "San Mateo County", year = 2010, progress_bar = F)
```

```{r}
saveRDS(dec_vars_2010, "dev_vars_2010.rds")
```

```{r}
saveRDS(dec_vars_2020, "dev_vars_2020.rds")
```


```{r}
HMB_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "Half Moon Bay")

HMB_blocks_2010 <- blocks_2010 %>% 
  st_centroid() %>% 
  .[HMB_boundary,] %>% 
  st_drop_geometry() %>% 
  left_join(blocks_2010 %>% select(GEOID10)) %>% 
  st_as_sf() %>% 
  select(GEOID10) %>% 
  left_join(SMC_pop_2010)

mapview(HMB_boundary) + mapview(HMB_blocks_2010, alpha.regions = 0, color = "red", lwd = 2)

```

```{r}
HMB_blocks_2020 <- blocks_2020 %>%
  .[HMB_boundary, ] %>% 
  select(GEOID20) %>% 
  left_join(SMC_pop_2020)
```

```{r}
HMB_blocks_2020_intersect <- HMB_blocks_2020 %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.)) %>% 
  st_intersection(
   HMB_blocks_2010 %>%
      select(GEOID10) %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = as.numeric(leftover_area / original_area),
    pop_2020 = pop_2020 * perc_area
  )
```


```{r}
HMB_blocks_2020_reshaped <- HMB_blocks_2020_intersect %>%
  st_drop_geometry() %>% 
  group_by(GEOID10) %>% 
  summarize(
    pop_2020 = sum(pop_2020, na.rm=T) %>% round()
  )
```

```{r}
projection <-  "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"
HMB_pop_2010_2020 <- HMB_blocks_2010 %>% 
  left_join(HMB_blocks_2020_reshaped) %>% 
  mutate(
    absolute_pop = (pop_2010-pop_2020) / as.numeric(st_area(.)) * 5280^2 *0.0015625)
```

```{r}
max <- max(abs(HMB_pop_2010_2020$absolute_pop))
absolute_pal <- colorNumeric(
  palette = "PiYG",
  domain = c(-max, max)
)
```

```{r}
leaflet(HMB_pop_2010_2020) %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    fillColor = ~absolute_pal(absolute_pop),
    label = ~round(absolute_pop),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1
  ) %>% 
  addLegend(
    pal = absolute_pal,
    value = c(-max,max),
    title = "Half Moon Bay White Population <br> Density Change (people per acre) <br> from 2010 to 2020"
  )
```

